FROM    quay.io/prometheus/busybox:latest
MAINTAINER  The Prometheus Authors <prometheus-developers@googlegroups.com>

COPY  prometheus                            /bin/prometheus
COPY  promtool                              /bin/promtool
COPY  documentation/examples/prometheus.yml