global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 20s
scrape_configs:
- job_name: cadvisor
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.0.22:8080

